AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  TableName:
    Type: String
    Default: 'VoiceStamp_connections'
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'


Globals:
  Function:
    Handler: lambda_function.lambda_handler
    Runtime: python3.9
    Environment:
      Variables:
        TABLE_NAME: !Ref TableName


Resources:
  VoiceStampWebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: VoiceStampWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
      Tags: 
        Product: VoiceStamp
        
  OnConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VoiceStampWebSocket
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: OnConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref OnConnectInteg

  OnConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VoiceStampWebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations

  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: onconnect/
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
      Tags: 
        Product: VoiceStamp

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VoiceStampWebSocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg

  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VoiceStampWebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisconnectFunction.Arn}/invocations

  DisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: disconnect/
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
      Tags: 
        Product: VoiceStamp

  SendVoiceRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref VoiceStampWebSocket
      RouteKey: send_voice
      AuthorizationType: NONE
      OperationName: SendVocie
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref SendVoiceInteg

  SendVoiceInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref VoiceStampWebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendVoiceFunction.Arn}/invocations

  SendVoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send_voice/
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VoiceStampWebSocket}/*'
      Tags: 
        Product: VoiceStamp

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - OnConnectRoute
    - SendVoiceRoute
    - DisconnectRoute
    Properties:
      ApiId: !Ref VoiceStampWebSocket

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      DeploymentId: !Ref Deployment
      ApiId: !Ref VoiceStampWebSocket
      AutoDeploy: true
      Tags: 
        Product: VoiceStamp

  VoiceStampConnectionsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: connectionId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Ref TableName
      Tags: 
        Product: VoiceStamp

  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - VoiceStampWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com

  DisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - VoiceStampWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DisconnectFunction
      Principal: apigateway.amazonaws.com

  SendVoicePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - VoiceStampWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SendVoiceFunction
      Principal: apigateway.amazonaws.com

Outputs:
  VoiceStampConnectionsTableArn:
    Value: !GetAtt VoiceStampConnectionsTable.Arn

  OnConnectFunctionArn:
    Value: !GetAtt OnConnectFunction.Arn

  DisconnectFunctionArn:
    Value: !GetAtt DisconnectFunction.Arn

  SendVoiceFunctionArn:
    Value: !GetAtt SendVoiceFunction.Arn

  WebSocketURI:
    Value: !Join [ '', [ 'wss://', !Ref VoiceStampWebSocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]